### ISSUE TITLE
能否clone下来san官网的代码，本地阅读api？

### ISSUE THREAD

**Issue by JHCan333** [baidu/san-website#112]
有的时候网速不太好，阅读san的api，会比较费劲；今天clone了san的代码，打算在本地跑一下，阅读api，但是不知道在哪里看？能否像ant-design之类的一样，clone下来，直接一跑就可以看啦？

**Comment by harttle** [comment]
参考 README： https://github.com/baidu/san-website

```bash
npm i
hexo s
```

**Comment by JHCan333** [comment]
点击start后会报404
