### ISSUE TITLE
我打算提交一个pr，但是报error:403

### ISSUE THREAD

**Issue by JHCan333** [baidu/san-website#114]
我在本地修改好了代码，打算提交pr ，但是报错了，我现在该咋办？
git push --set-upstream origin release_jhc
remote: Permission to baidu/san-website.git denied to JHCan333.
fatal: unable to access 'https://github.com/baidu/san-website.git/': The requested URL returned error: 403

**Comment by Justineo** [comment]
你需要先 push 到自己的 fork repo，然后再发起 PR。

**Comment by JHCan333** [comment]
好的，我的改好了，多谢指点
